name: Passing data between jobs
on: push
jobs:
  job_1:
    name: Upload file
    runs-on: ubuntu-latest
    steps:
      - run: echo $name > name.txt
        env:
          name: Ahmet Katranci
      - uses: actions/upload-artifact@v2
        with:
          name: name
          path: "./name.txt"
  job_2:
    name: Download file
    runs-on: ubuntu-latest
    needs: job_1
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: name
      - run: cat name.txt
